### PR TITLE
use kebab-case arguments for jest process

### PR DESCRIPTION
**Pull request by vhdirk**
See https://github.com/jest-community/vscode-jest/issues/923 for context

### CODE REVIEW

**Review by connectdotz — COMMENTED** [review]
thanks for the PR! 

tests will need to be adjusted as well...

**Comment by vhdirk** [comment]
Fixed the tests

**Comment by aberasarte** [comment]
I came across the Angular 14 cli issue as well. Any chance to merge this? 

Thanks!

**Comment by connectdotz** [comment]
closed via #103

**Pull request closed without merging**
