### PR TITLE
expose fullName and ancestorTitles for assertions and address parser parity

### PR DESCRIPTION
**Pull request by connectdotz**
- expose `fullName` and `ancestorTitles` properties from jest assertions. This allows clients to build "context", describe/test hierarchy, for the tests.
- fix a few parser related issues

### CODE REVIEW

**Comment by connectdotz** [comment]
@firsttris I think you are most familiar with the parser now, can you review this PR to make sure I didn't miss anything obvious... thanks!

**Comment by firsttris** [comment]
looks good to me!

**Comment by connectdotz** [comment]
thanks @firsttris

**Comment by connectdotz** [comment]
@seanpoulter do you want to review it before I merge this?

**Pull request merged**
